#include "expression/unicodes.hpp"
// Generated by gperf for O(1) perfect hash symbol lookups
#include "lookup.hpp"

namespace expression {

    const std::uint32_t Unicodes::invalid = 0xFFFD;

    Unicodes::Unicodes() = default;

    void Unicodes::compose(const std::string_view name, const std::uint32_t codepoint, const Category category) {
        overrides.insert_or_assign(std::string(name), Symbol{codepoint, category});
    }

    void Unicodes::dispose(const std::string_view name) {
        overrides.erase(name);
    }

    std::optional<Unicodes::Symbol> Unicodes::query(const std::string_view name) const noexcept {
        if (const auto iterator = overrides.find(name); iterator != overrides.end()) {
            return iterator->second;
        }

        if (const auto* entry = Lookup::query(name.data(), static_cast<unsigned int>(name.size()))) {
            return Symbol{entry->codepoint, static_cast<Category>(entry->category)};
        }

        return std::nullopt;
    }

}